"""initial schema

Revision ID: ad050b485cf4
Revises:
Create Date: 2026-09-11 19:08:18.254966

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "ad050b485cf4"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "medium",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "modality",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("pipeline", sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "source",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "company",
                "government",
                "organization",
                "media",
                "person",
                "other",
                name="sourcetype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("confirmed", sa.Boolean(), nullable=False),
        sa.Column("credit", sa.String(length=1), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "outlet",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("entry", sa.Text(), nullable=True),
        sa.Column("medium_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["medium_id"],
            ["medium.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id", "name"),
    )
    op.create_table(
        "intelligence_item",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("statement", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "lead",
                "candidate",
                "verified",
                "undetermined",
                "noise",
                "rejected",
                name="itemstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("rating", sa.String(length=2), nullable=True),
        sa.Column("retracted", sa.Boolean(), nullable=False),
        sa.Column(
            "mode",
            sa.Enum("manual", "automated", name="itemmode", native_enum=False),
            nullable=False,
        ),
        sa.Column("modality_id", sa.Integer(), nullable=False),
        sa.Column("medium_id", sa.Integer(), nullable=False),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("original_snapshot", sa.Text(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=True),
        sa.Column("outlet_id", sa.Integer(), nullable=True),
        sa.Column("provenance_source_id", sa.Integer(), nullable=True),
        sa.Column("event_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["medium_id"],
            ["medium.id"],
        ),
        sa.ForeignKeyConstraint(
            ["modality_id"],
            ["modality.id"],
        ),
        sa.ForeignKeyConstraint(
            ["outlet_id"],
            ["outlet.id"],
        ),
        sa.ForeignKeyConstraint(
            ["provenance_source_id"],
            ["source.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_intelligence_item_mode"), "intelligence_item", ["mode"], unique=False)
    op.create_index(
        op.f("ix_intelligence_item_source_id"), "intelligence_item", ["source_id"], unique=False
    )
    op.create_index(
        op.f("ix_intelligence_item_status"), "intelligence_item", ["status"], unique=False
    )
    # ### end Alembic commands ###

    # 参考数据：媒介封闭集合（术语表 §六）；互联网仅自动拉取、不经录入素材页（doc-07 §2.3）
    medium_table = sa.table(
        "medium",
        sa.column("code", sa.String),
        sa.column("name", sa.String),
        sa.column("description", sa.Text),
    )
    op.bulk_insert(
        medium_table,
        [
            {"code": "internet", "name": "互联网", "description": "系统自动拉取，不经人工录入"},
            {"code": "user_interview", "name": "用户访谈", "description": None},
            {"code": "industry_exhibition", "name": "行业展会", "description": None},
            {"code": "industry_exchange", "name": "行业交流", "description": None},
            {"code": "meeting_discussion", "name": "会议讨论", "description": None},
            {"code": "document_reading", "name": "文档阅读", "description": None},
        ],
    )

    # 参考数据：载体集合（术语表 §六）；处理管线随附件载体任务（IIH-01.09~11）启用
    modality_table = sa.table(
        "modality",
        sa.column("code", sa.String),
        sa.column("name", sa.String),
        sa.column("pipeline", sa.String),
    )
    op.bulk_insert(
        modality_table,
        [
            {"code": "webpage", "name": "网页", "pipeline": None},
            {"code": "audio", "name": "录音", "pipeline": "asr"},
            {"code": "text", "name": "文字", "pipeline": None},
            {"code": "image", "name": "图片", "pipeline": "ocr"},
            {"code": "document", "name": "文档", "pipeline": "parse"},
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_intelligence_item_status"), table_name="intelligence_item")
    op.drop_index(op.f("ix_intelligence_item_source_id"), table_name="intelligence_item")
    op.drop_index(op.f("ix_intelligence_item_mode"), table_name="intelligence_item")
    op.drop_table("intelligence_item")
    op.drop_table("outlet")
    op.drop_table("source")
    op.drop_table("modality")
    op.drop_table("medium")
    # ### end Alembic commands ###
